name: QrScannerIOS
options:
  bundleIdPrefix: com.example.qrscanner
  deploymentTarget:
    iOS: "16.0"
targets:
  QrScannerIOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.qrscanner.ios
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: QrScanner
        UILaunchScreen:
          UIColorName: ""
        NSCameraUsageDescription: "Camera access is required to scan EV0 serials."
